### ISSUE TITLE
deploy minified and versioned assets (js+css)

### ISSUE THREAD

**Issue by clkao** [datproject/dat.land#105]

**Comment by laurengarcia** [comment]
Just for posterity: Am finding that `uglify-js`-based minifiers (which includes npm's `minifyify`, `minifier`, etc)  cannot minify template literals and generally aren't going to play nicely with ES6 features. This is true even when trying to use `uglify-js` as just a minifier without "mangling". The parser just stops altogether.

Uglify-Js issue re: template literals in harmony branch of `uglify-js`:
https://github.com/mishoo/UglifyJS2/issues/1147

And general discussion about what to do with >ES5 features in future:
https://github.com/mishoo/UglifyJS2/issues/1181

**Comment by laurengarcia** [comment]
npm `minify` module also a fail.

**Comment by laurengarcia** [comment]
ok, after hunting and pecking for quite a while it seems there is no solution, unless we either write a minifier ourselves or <shudder> babelify the whole thing. tried babelify with both es2015 and es2016 transforms and neither of them transformed the template literals -- not sure what i'm doing wrong or if this is even worth it. anyway, in package.json i did this:

`"babelify-js": "browserify -d public/js/tmp.js > public/js/tmp.min.js -t [babelify --no-sourceMaps --presets [ es2016 ]]"`

**Comment by mafintosh** [comment]
would that yoyofy thing solve this?

**Comment by laurengarcia** [comment]
im afraid not, yo-yoify also uses template literals. it just changes what yoyo does "under the hood" -- instead of voodoodom, it uses actual calls into browser document.

**Comment by laurengarcia** [comment]
https://github.com/shama/yo-yoify#how-this-works

**Comment by laurengarcia** [comment]
ok, yoshua says this will do it:
https://github.com/yoshuawuyts/es2020

**Comment by laurengarcia** [comment]
Done.
