### ISSUE TITLE
implement back/forward button (client-side routing)

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#110]
should be a fun task. best guess on how to approach it: implement a reducer that keeps track of archive key as a minidux reducer that uses an array to keep track of the archives we've seen.

im guessing the client-side routing should also keep track of what directory level and indiv. file we are at within the archive? will have to gather requirements around this a little before implementing. plz chime in if you have set ideas about what you'd like to see.

**Comment by juliangruber** [comment]
+1

it's also probably easier and more ux safe to use the url for state instead of storing it in an array. something like `dat.land/KEY/FOLDER/FILE`, and then using push state and a router like https://github.com/substack/single-page

**Comment by laurengarcia** [comment]
agree, if you mean by "use the url for state instead of storing in an array", you mean use window.history.pushState() api. <-- i agree. with minidux in the mix, i imagine we'll need to also notify minidux for changes to the native browser api, tho, even if all it does is poll the window.history api when location changes.  that way our other reducers (& components) get updates on which archive we're looking at. 

later on i think it will be interesting to layer window history with archive append-only log history as well.

**Comment by karissa** [comment]
Ah yeah, I'm into using the url. I used to use https://www.npmjs.com/package/page and hadn't heard of @substack 's single-page.

**Comment by juliangruber** [comment]
page.js is great as well, both should work just fine.

@laurengarcia with both libraries you get callbacks on location change, which you then can tell minidux about.
