### ISSUE TITLE
signalhub status

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#114]
If you have multiple browser tabs, the connection to signalhub is blocked due to per-host connection limit (hello this is 2016?) and making the UI non-responsive.

There should be an indicator if signalhub is not responsive after a few seconds.

Moved from https://github.com/karissa/hyperdrive-ui/issues/23

**Comment by clkao** [comment]
would it help if the signalhub server speaks http/2?

**Comment by karissa** [comment]
we're falling back on server-side rendering in this case it seems
