### ISSUE TITLE
*.dat.land DNS

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#132]
@maxogden what do you use for the dns for dat.land? 

We set up some subdomains for testing environments on dat.land and found that the dns is not set up properly. http://uat.dat.land is now set up and seems to work on the correct ip/port, but not dns ('user acceptance testing' @laurengarcia) 

You could add some of us (myself @laurengarcia @clkao) if possible so we stop bugging ya! :)

**Comment by maxogden** [comment]
i use name.com, I don't think I can add anyone else to the management UI

Here's the current settings. if someone tells me what to set i'll set it, just ping me on IRC

<img width="981" alt="screen shot 2016-07-11 at 2 53 01 pm" src="https://cloud.githubusercontent.com/assets/39759/16748129/40187518-4777-11e6-93e3-7325294cd4c1.png">

**Comment by maxogden** [comment]
added a *.dat.land A record
