### ISSUE TITLE
Hint while file is being added to archive

### ISSUE THREAD

**Issue by clkao** [datproject/dat.land#136]
The queued files that is being added (but not in the archive yet) should be listed below the drag&drop area, so the user knows something is happening and won't attempt to drop again.

**Comment by Kriesse** [comment]
@laurengarcia Probably related: I tried having a more explicit drag&drop area (which on click would make you select a file from finder) in this mockup below, I think it would help to explain to the user that they can add files. 

![image](https://cloud.githubusercontent.com/assets/53684/16847895/7da1c4b0-49f3-11e6-83d8-06e8a5ac4f92.png)

Maybe this would also be a good place for a hint on the status of uploaded files?
Let me know if I can help with a mockup and/or CSS.

**Comment by laurengarcia** [comment]
ah that looks fantastic -- im working on a PR right now and got the progress bar emitting the stats for the read&write progress, was just about to start with the ui, and there it is! looks awesome.

**Comment by laurengarcia** [comment]
@Kriesse Where in this do you imagine the "hint" would go -- note that right now it consists of a file list that has size and its own progress bar to indicate that each file is being written to the dat. once its addded. right now i have the "hint" (aka file list queue) attaching above the dat archive file list.

**Comment by Kriesse** [comment]
@laurengarcia Ah yeah! I had originally thought the "Add Files" button / drop area could change into "Files uploading…" while files are uploading. But attaching a file list queue sounds much better.

Something like this? (progress bars not mocked up yet)

![image](https://cloud.githubusercontent.com/assets/53684/16852237/840f5330-4a07-11e6-80ed-40212254d40a.png)

**Comment by laurengarcia** [comment]
@Kriesse yes! exactly. i have a progress bar working (theoretically, right now its just emitting stats that i need to turn into ui) so i was thinking that could go where you have the "just now" on the far right. was also thinking the "just added" file queue should append above the archive list so its obvious when you drag and drop what is happening. if you already had a bunch of files in the archive that is.

**Comment by laurengarcia** [comment]
Complete: https://github.com/datproject/dat.land/pull/150
