### ISSUE TITLE
fix uat.dat.land ssl cert

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#143]
we could get an ssl certificate from lets encrypt with a bunch of different subdomains
the problem is letsencrypt doesn't do wildcards

**Comment by karissa** [comment]
uat
staging
dev
test
stats
analytics
api
signalhub1
signalhub2
signalhub3
dns1
dns2
dns3

**Comment by mafintosh** [comment]
if someone can tell me how to an expense report for datland stuff i'll make wildcards work by buying a wildcard cert

**Comment by karissa** [comment]
@mafintosh it seems like the subdomains still aren't working, is there something we have left to do?

**Comment by mafintosh** [comment]
ssl enabled on all subdomains now. nginx will do a perm redirect to https if a http request comes in. the redirect is not enabled on the root domain (dat.land) because i didn't want to change your existing conf.

**Comment by mafintosh** [comment]
i'd suggest using taco-nginx to deploy apps to dat.land. then we don't need to ever change our nginx setup :)
