### ISSUE TITLE
use memory for content

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#151]
we can still use leveldb for the metadata but lets use memdb for the block file contents.

**Comment by clkao** [comment]
This probably means hypercore needs to support different storage for feeds?

**Comment by clkao** [comment]
also if there's something we want to track with the e2e tests (such as replicate or retreival speed) we should add them

**Comment by karissa** [comment]
@clkao yes it does, i think we can use https://github.com/mafintosh/random-access-memory

**Comment by karissa** [comment]
I tried to use random-access-file but it deletes the buffer after it finishes writing. Need to use a different module

**Comment by karissa** [comment]
mafintosh fixed a critical bug in 2.1.0 for https://github.com/mafintosh/random-access-memory so we should be able to use that here now
