### ISSUE TITLE
bug: two webrtc-swarm instances are created for `#<archiveId>` routes

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#160]
ogd: "the main function get called twice when you load a dat.land/#/somehash address, once main is triggered for the initial page load then again because the onhashchange handler triggers it again, so actually two webrtc-swarm instances get created almost a the same time and they both talk to the signalhub"

protip: add localStorage.debug = 'webrtc-swarm' at the top of app.js for more debug

**Comment by clkao** [comment]
I think this is now fixed.

However if we are at archiveId route, and loads another dat, are we supposed to reuse the same webrtc-swarm?

**Comment by karissa** [comment]
I don't think we would re-use the same webrtc-swarm because each archiveId is server-rendered so there has to be a refresh
