### ISSUE TITLE
Server-render archive metadata in <head> tag and page's header

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#162]

**Comment by clkao** [comment]
@laurengarcia do we have a list of required fields to be rendered for this issue?

**Comment by laurengarcia** [comment]
no, but this is probably a good spot for them. suggest:
* title (key or archive metadata.title)
* meta description 
* meta author
* meta keywords

**Comment by clkao** [comment]
assuming everything is coming from dat.json, this is pending #216

**Comment by karissa** [comment]
yeah from dat.json now sure. in the future it could come from the database once we have user accounts and repos.
