### ISSUE TITLE
Migrate individual file rendering 

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#173]
We're going to do this in a sliding panel. @Kriesse has the design.

**Comment by clkao** [comment]
https://github.com/karissa/yo-fs/pull/6 made yo-fs accept onclick handler that overrides the default behaviour.

**Comment by clkao** [comment]
The design is here: https://github.com/datproject/design/issues/17#issuecomment-232702988

**Comment by laurengarcia** [comment]
temporarily assigning this to myself per conversation with @Kriesse. scope for now is just stubbing out a template with the sliding panel from the issue cl linked to above that she can pick up and start css/html'ing.

**Comment by clkao** [comment]
This is done by #240 feature-wise right?
