### ISSUE TITLE
Decide on server-side asset cacheing strategy/library

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#177]

**Comment by laurengarcia** [comment]
Update: I spent the evening evaluating different flavors of artisenal static asset server solutions and am now of the opinion that we should just use nginx to serve assets from /client and /public dirs, both locally and in prod. For prod+uat, we'll aggressively cache and gzip assets in  /public since that's where our bundles get built and for /client (which we'll use to serve assets in `?debug=true` mode), we'll have no cacheing whatsoever. Hit me up if you have other ideas.

**Comment by juliangruber** [comment]
while nginx certainly is a good solution, i'd say we wait until dat.land gets heavy usage. it's tempting to start optimizing stuff like this before every part of the app completely works...
