### ISSUE TITLE
server-side choo logger

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#180]

**Comment by juliangruber** [comment]
can you explain this issue a bit further?

**Comment by laurengarcia** [comment]
on the server side we're calling choo's .toString() method to render the html. i haven't looked at the choo logger too much so I don't even know if there are any debugging methods for .toString(), but it would be nice to have something that blows up nicely when there's an error. if there's not anything, we can let it go.

**Comment by laurengarcia** [comment]
yeah, choo logger is client-side only. on the server choo just throws an assertion error, which i guess is enough for development.
