### ISSUE TITLE
UX: Implement dat-data.com -> dat.land flow (see mocks)

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#185]
https://drive.google.com/drive/u/0/folders/0B9PzWmfA2r7VQkRwTGJqVnNBV1k

**Comment by Kriesse** [comment]
## Entry Point 1: User lands on dat-data.com, follows CLI 3-step-tutorial and enters dat-link

![01-dat-data com user follows tutorial enters dat-link](https://cloud.githubusercontent.com/assets/53684/17491367/a7997bf6-5da7-11e6-82ae-ddc6a411ee78.png)

## Entry Point 2: User lands on dat.land, either drops files, or enters dat-link

![01-dat land - new user sees this when they land on dat land without a hash](https://cloud.githubusercontent.com/assets/53684/17491369/a7b12a8a-5da7-11e6-9426-60c780770459.png)

## Dat.land: User sees single dat view of the dat they just created (Read & Write)

![02-dat land read only - single dat view](https://cloud.githubusercontent.com/assets/53684/17491374/a7c2d19a-5da7-11e6-9b3b-b40ab53d7c9c.png)

## Dat.land: User sees single dat view of the dat-link they just entered (Read only)

![02-dat land read write - single dat view](https://cloud.githubusercontent.com/assets/53684/17491370/a7bfa6e6-5da7-11e6-9071-3703f2788e71.png)

## File Preview

![03a-dat land - single dat view preview file - full screen](https://cloud.githubusercontent.com/assets/53684/17491371/a7c01856-5da7-11e6-85ea-e483714f893b.png)

## File Preview: File (e.g. .csv) too big, can't preview more

![03b-dat land - single dat view preview file - full screen - done loading](https://cloud.githubusercontent.com/assets/53684/17491372/a7c136a0-5da7-11e6-802c-d9c059582db5.png)

## File Preview: File (e.g. .png) too big, can't preview at all

![03c-dat land - single dat view preview file - full screen - can t display file type](https://cloud.githubusercontent.com/assets/53684/17491373/a7c2c2c2-5da7-11e6-8212-9dd91ac99be3.png)

**Comment by Kriesse** [comment]
## Error when user tries to upload file >20MB

![04-dat land-upload-error-file-too-big](https://cloud.githubusercontent.com/assets/53684/17491886/ca812af4-5da9-11e6-9839-037c19d21295.png)

**Comment by juliangruber** [comment]
I really like this! Only the two lines "Dat is a dataset sharing system. Give it a try" seem a little out of place, especially that "Give it a try:" is still in the header although it belongs to the content area.

CSV view by the way looks super rad!

**Comment by karissa** [comment]
It all looks great!

Is there an error state for "upload failed" on the file list screen? I imagine we need to have some sort of general error state for the app too, that allows people to report a bug

**Comment by karissa** [comment]
I realize this has become one big mega issue XD didn't mean to do that!

**Comment by Kriesse** [comment]
@karissa Good point, will mock up the error state!

**Comment by Kriesse** [comment]
### Dat.land: Upload failed 

![04-dat land-upload-fail-error](https://cloud.githubusercontent.com/assets/53684/17511330/b7b5c2f8-5e22-11e6-8344-903c77f19c0d.png)

### Dat.land: Upload in progress

![04-dat land-upload-in-progress](https://cloud.githubusercontent.com/assets/53684/17511354/c9520314-5e22-11e6-89e3-e1629bc56206.png)

**Comment by Kriesse** [comment]
@juliangruber Yes, agreed, also not happy yet with the big green header. Will try out different styles in the browser!
