### ISSUE TITLE
Is there no way of browsing data?

### ISSUE THREAD

**Issue by COLABORATI** [datproject/dat.land#211]
Is there anything broken with dat.land? I am seeing this: 
![2016-08-30_empty-dat-land](https://cloud.githubusercontent.com/assets/6514273/18108644/79b92246-6f0d-11e6-87b0-eca1f43594a1.png)

But I was expecting something like [this](http://academictorrents.com/browse.php?cat=6)

If there is nothing broken, then you should add some more decription that explains why there is nothing to see. 

Am I misunderstanding the concept? Is dat.land not a browser of available open data? 

This issue can also give you a hint about what could be optimized to present this project: show some data and how easy it is browsable and shareable with dat right on the frontpage!

**Comment by COLABORATI** [comment]
uhmm, this project needs some serious clean-up on self presentation. 
I now found  a [blog post](http://dat-data.com/blog/2016-02-01-announcing-publicbits) about the [publicbits](http://publicbits.org) website - but that website just show a 502 nginx error:
![2016-08-31_dat-publicbits-502](https://cloud.githubusercontent.com/assets/6514273/18109011/6862a362-6f0f-11e6-9065-a7f9ca472e02.png)

The last sentence of the blog link to the publicbits [repo](https://github.com/publicbits/publicbits.org) which then redirects to this repo. I am now totally confused about what to expect from this project.
Is it dead already?

**Comment by COLABORATI** [comment]
BTW, please do not hate me for this, but the video in that blog post looks like it was made by the [Yes Men](https://en.wikipedia.org/wiki/The_Yes_Men). I like the Yes Men very much, but for a serious data project with a large budget, well, I expected some more, uhmm, content. Please do not feel offended, I am just open about my perception of that presentation. It is really funny and I had a good laugh, but you still should consider removing that "presentation" as people might think this project is just fake.

**Comment by karissa** [comment]
We'll be adding user accounts and published datasets in the next version. Stay tuned!
