### ISSUE TITLE
'-1 sources'

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#226]
it should never hit -1 sources but it happens when you open a dat and connect then close it on the other side, sometimes i think that it's firing the 'peer disconnected'  event twice

**Comment by clkao** [comment]
Note that the state here is taken from `state.swarm.connections` directly, so it'll be a bug in the swarm implementation.

**Comment by karissa** [comment]
thanks, made a PR to hybrid-swarm to fix this
