### ISSUE TITLE
import queue is not receiving `cwd`

### ISSUE THREAD

**Issue by laurengarcia** [datproject/dat.land#235]
fixing this depends on https://github.com/datproject/dat.land/issues/234

**Comment by karissa** [comment]
it seems to be called `root` not `cwd` and it is being passed via: https://github.com/datproject/dat.land/blob/master/client/js/components/hyperdrive/index.js#L25

**Comment by laurengarcia** [comment]
a reminder for me; i need to update hyperdrive-import-queue to make sure its getting it as well.

**Comment by karissa** [comment]
@laurengarcia i took a look at it seems like you're doing it there https://github.com/laurengarcia/hyperdrive-import-queue/blob/master/index.js#L48
