### ISSUE TITLE
previewing pdfs and csvs

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#240]
the dom isn't updating as each new data point comes in, or in the case of a pdf, when the data has finished loading completely, it should redraw.. but it is not.

**Comment by karissa** [comment]
reproduce by trying to preview a csv or pdf

**Comment by laurengarcia** [comment]
can you clarify: "the dom isn't updating as each new data point comes in" <-- what does that mean specifically?

**Comment by laurengarcia** [comment]
hm, its not rendering even a simple text file right now either... ?
