### ISSUE TITLE
share button?

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#255]
@Kriesse im thinking we should have a 'share' button on the browser app, like this: 

<img width="1181" alt="screen shot 2016-09-12 at 9 00 57 pm" src="https://cloud.githubusercontent.com/assets/633012/18448591/064e7e4a-792c-11e6-9598-58e175fd3fd5.png">

It could copy the link to the clipboard automatically, or perhaps work like google doc's modal.. what do you think?

**Comment by Kriesse** [comment]
I like the CloudApp modal, which gives you the option to share via email, and also to copy the link to the clipboard:
![image](https://cloud.githubusercontent.com/assets/53684/18551465/cf1d3892-7b58-11e6-901f-5c213c8eae31.png)
For our usecase I'd put more emphasis on copying the link than on the share-via-email feature.

**Comment by karissa** [comment]
doing this on the desktop app closing this
