### ISSUE TITLE
broken filelist with cli+webrtc 

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#266]
This dataset here published by @mafintosh does not work with dat.land. He has published it over webrtc and cli using hypermirror. The file list appears correctly but it goes blank after rehydration.

021f66c30327bd9e13908bf1c1d66d83fd962ec6aa4539f6c682e7a2e9301ba1

**Comment by clkao** [comment]
the symptom sounds like it's published through discovery swarm but not properly through webrtc.  Is the hypermirror's --rtc working?

**Comment by karissa** [comment]
Yeah actually, you might be catching onto something. Definitely found it difficult to install all of the required dependencies to get --webrtc working on my linux box.

**Comment by laurengarcia** [comment]
This particular symptom is definitely happening during rehydration phase of the app on the client side. Am spelunking right now, but basically even when we are rehydrating from state object (which is well-formed) that gets passed from server to client, we are seeing this problem. So its definitely in rehydration. Am working on a better pattern and found a couple of ancillary bugs on Friday but haven't found the culprit exactly yet. (That's not to say that @clkao might not be onto something else, tho , too).

**Comment by laurengarcia** [comment]
Ok, I thought this would have been a choo issue, but after closer investigation, it is definitely not; choo seems A-ok. Looks like an issue where hyperdrive-ui (yo-fs) and choo are fighting/stomping on each other because they are both using `yo-yo`under the hood for dom diffing(?). It seems like there is some race condition ensuing when there is long array in the `archive.entries` list that gets populated from the state object passed in from server.

**Comment by karissa** [comment]
Maybe this also surfaces that we should be paging the file lists too (as we do with csv). In theory someone could put 10,000 files in a day..

**Comment by laurengarcia** [comment]
@karissa Yes, that is definitely a thing, was also thinking about that ^^. This bug has been really useful in that it has forced a revisit of alot of things. Another thing I noticed, and this may be part of the problem as well, is that we are not server-rendering directories properly in server/components/hyperdrive. d'oh!

**Comment by karissa** [comment]
I think this is fixed now, I'm consistently seeing the filelist.
