### ISSUE TITLE
uploaded archive fs ui not cleared after hitting "New archive"

### ISSUE THREAD

**Issue by clkao** [datproject/dat.land#269]
1. upload a bunch of files
2. click new archive
3. now see the file list in a weird state of uploads at 0% progress.
![screen shot 2016-09-18 at 10 29 05 am](https://cloud.githubusercontent.com/assets/69736/18612382/ed321292-7d8a-11e6-9c75-96e40bbee6f9.png)

**Comment by laurengarcia** [comment]
ah, i think i know what that might be.

**Comment by laurengarcia** [comment]
@clkao: can you pull this branch down and see if this fixes the problem for you? 
https://github.com/datproject/dat.land/tree/issue-269

**Comment by clkao** [comment]
@laurengarcia seems worky!

**Comment by laurengarcia** [comment]
this should have fixed it:
https://github.com/datproject/dat.land/pull/288

**Comment by laurengarcia** [comment]
this one will also help choo to be more responsive to user-initiated actions (i.e. hitting `new archive` button) during import-queue rendering: https://github.com/datproject/dat.land/pull/290
