### ISSUE TITLE
opening a new item after another item shows the old item for a second

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#281]
1. open the following dataset: http://dat.land/7498eea031f52cfc61f8a24adb1c2a7050e6d197b1f3190b0370c6a10e23287a

2. Open one of the files
3. Open another file
4. See one of the files briefly before the other one loads

**Comment by karissa** [comment]
this seems to have fixed

**Comment by joehand** [comment]
I thought about it really hard while I was on the plane trying to get signalhub and local dat.land working :upside_down_face:.
