### ISSUE TITLE
cli-shared cache for a dat's metadata persists after reload

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#285]
1. share a dat on the cli
2. open the link in dat.land
3. on your desktop, add a file to the dat 
4. you *should* see the new file in the filelist

Instead, you don't see it update at all. The filelist remains the same and the new file does not appear.

If you refresh, you'll see the same metadata. You would expect to see the new file. But it does not appear.

If you restart the server,
and delete the dat.land leveldb database,
then when you open the link, you'll see the new filelist. Bravo.

**Comment by clkao** [comment]
Do you see `Source: 1`?  It's very likely the cli is not sharing over webrtc by default.

**Comment by juliangruber** [comment]
> Do you see Source: 1? It's very likely the cli is not sharing over webrtc by default.

Wouldn't that mean that you can't see the dat on dat.land at all?

**Comment by clkao** [comment]
The server side rendering currently works over discovery channel!  That'd explain the behaviour that refreshing brings contents up-to-date.
