### ISSUE TITLE
Incorrect server-rendered contents

### ISSUE THREAD

**Issue by clkao** [datproject/dat.land#289]
This is happening on archive-refactor branch as well, the server-rendered fs content has lots of empty directories, which is corrected after client rehydration.

1. use dat cli to share a directory (in my case ./command in the dat tree).
2. open devtool -> source, add a breakpoint at client/model/archive.js:subscriptions
3. load the datlink and observe incorrect empty directories.
4. hit continue in the devtool, and see contents corrected.

![screen shot 2016-09-26 at 12 56 15 am](https://cloud.githubusercontent.com/assets/69736/18816838/2aee7dce-8384-11e6-9ad2-bf1bce1af2a5.png)

**Comment by laurengarcia** [comment]
+1 I also started noticing this recently as well
