### ISSUE TITLE
find new name

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat.land#300]

**Comment by karissa** [comment]
publicbits.org

**Comment by karissa** [comment]
didn't we already have a naming thread somewhere? @maxogden

**Comment by karissa** [comment]
myfolder
datafolder
sciencefolder

**Comment by yoshuawuyts** [comment]
I quite like `dat.land` to be honest - feel it's both easy to remember and memorable :sparkles:

**Comment by joehand** [comment]
> I quite like dat.land to be honest - feel it's both easy to remember and memorable ✨

The issue is that there is also http://www.datland.com/ and we were worried about people getting there and confused and potiential copyright issues. 

> didn't we already have a naming thread somewhere? @maxogden

We had one for the [non-profit name](https://github.com/datproject/events/issues/14).

**Comment by joehand** [comment]
datfolder.org/datfolder.com
