### ISSUE TITLE
dat.land crashes after sustained use

### ISSUE THREAD

**Issue by karissa** [datproject/dat.land#304]
dat.land will start timing out after sharing a few different dats. It also makes the server slow (slow to ssh). I wonder if the lru cache is filling up in server/haus.js.

**Comment by karissa** [comment]
Could be that the box is too small memory-wize. @maxogden has the keys to up the DO box for dat.land to 1GB or more

**Comment by Fastidious** [comment]
dat.land seems to be down now.

**Comment by karissa** [comment]
tried to fix this in most recent commit - https://github.com/datproject/dat.land/commit/ef7eecce5cc7dac1258ebc7dd4bee6b6eb010ed8

**Comment by karissa** [comment]
log before the crash
```
GET /public/img/create-new-dat.svg
GET /public/img/dat-data-blank.png
GET /public/img/link.svg
GET /public/img/question.svg
GET /public/img/dat-data-blank.png
GET /public/img/dat-data-blank.png
router.js /:archiveKey route error: Invalid key
GET /public/js/app.min.d110185467f209f97c6ea06542c9f656.js
GET /public/js/browser-warning.c93d63fd949e64ef191145d802e2ac96.js
GET /public/css/main.min.292db7a7a725f73791125dcdfc479ec1.css
router.js /:archiveKey route error: Invalid key
router.js /:archiveKey route error: Invalid key
router.js /:archiveKey route error: Invalid key
router.js /:archiveKey route error: Invalid key
router.js /:archiveKey route error: Invalid key
router.js /:archiveKey route error: Invalid key
/home/admin/.npm/bin/taco-nginx: line 86: kill: (22664) - No such process
```

**Comment by karissa** [comment]
attempt at fix: https://github.com/datproject/dat.land/commit/2ea98a29a208e22b271764d327079e873ac124d7

redeployed to dat.land for more testing

**Comment by karissa** [comment]
looks like this is fixed!
