### ISSUE TITLE
download from web not working

### ISSUE THREAD

**Issue by dschneiderch** [datproject/dat.land#309]
I'm really interested in the idea of dat but the browser download button isn't working for me.
When I click Download i get no response. I'm in chrome, no ad blocker. 
am i missing something?

dat.land/a724a3fef5f190ea91cd038d9f1d19ef4c24380ff2db6912cb7aa4c0b9c6315a

**Comment by karissa** [comment]
Ah yes this is because we download content from webrtc, which is from the desktop app or with the `dat --webrtc ...` option. We plan on moving to websocket server connections in the next version which will allow for downloading from servers without webrtc. cc @mafintosh @maxogden
